# Generated by Django 3.0.3 on 2020-04-16 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('secretSanta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 16, 13, 57, 23, 977958, tzinfo=utc)),
        ),
    ]
